// GENERATED by tool/gen_tokens.dart from docs/design/tokens.json. Do not edit:
// change the tokens there, then run `dart run tool/gen_tokens.dart` from app/.

import 'package:flutter/animation.dart';
import 'package:flutter/painting.dart';

/// Every colour and shadow token in one theme: Studio light or Studio dark.
/// The stage, caption and ripple colours are the same in both.
class SaPalette {
  const SaPalette({
    required this.paper,
    required this.surface,
    required this.surfaceSunk,
    required this.line,
    required this.lineStrong,
    required this.ink,
    required this.ink2,
    required this.ink3,
    required this.primary,
    required this.onPrimary,
    required this.cue,
    required this.onCue,
    required this.focus,
    required this.cueStress,
    required this.cuePause,
    required this.cueBreath,
    required this.cueSlower,
    required this.cueFaster,
    required this.cueEnergy,
    required this.tintSlower,
    required this.tintFaster,
    required this.tintSelect,
    required this.rec,
    required this.danger,
    required this.success,
    required this.warning,
    required this.stage,
    required this.stageScrim,
    required this.stageText,
    required this.stageTextRead,
    required this.stageLine,
    required this.stageChrome,
    required this.stageChromeText,
    required this.stageStress,
    required this.stagePause,
    required this.stageBreath,
    required this.stageSlower,
    required this.stageFaster,
    required this.stageEnergy,
    required this.stageTintSlower,
    required this.stageTintFaster,
    required this.stageRec,
    required this.stageOk,
    required this.stageWarn,
    required this.stageGlass,
    required this.stageGlassEdge,
    required this.captionText,
    required this.captionPlate,
    required this.captionWaiting,
    required this.ripple,
    required this.shadowFloat,
  });
  /// Studio page background: library, editor, settings.
  final Color paper;
  /// Cards, sheets, dialogs and inputs raised on paper.
  final Color surface;
  /// Recessed fields: segmented-control tracks, text areas, meters.
  final Color surfaceSunk;
  /// Decorative hairlines and dividers only; never the only edge of a control.
  final Color line;
  /// Borders of inputs, outlined buttons and toggles (3:1 on paper, surface and surface-sunk).
  final Color lineStrong;
  /// Primary text and icons on paper, surface and surface-sunk.
  final Color ink;
  /// Secondary text: subtitles, helper text, inactive tabs, on paper and surface.
  final Color ink2;
  /// Meta text: timestamps, word counts, captions; on paper, surface and surface-sunk.
  final Color ink3;
  /// Fill of the one primary action on a screen (Record, Mark up, Save).
  final Color primary;
  /// Text and icons on primary.
  final Color onPrimary;
  /// The signature amber: brand mark, the stressed-word highlight, the Accept-all fill. A fill,
  /// never text on light grounds.
  final Color cue;
  /// Text and icons on cue.
  final Color onCue;
  /// Keyboard focus ring: 2px solid, 2px offset, on every Studio surface.
  final Color focus;
  /// Stressed words: text colour in the editor. Studio only; the stage uses the matching stage-
  /// token.
  final Color cueStress;
  /// Pause and long-pause glyphs after a word, and the PAUSE hold badge. Studio only; the stage uses
  /// the matching stage- token.
  final Color cuePause;
  /// Breath glyph after a word and the BREATHE hold badge. Studio only; the stage uses the matching
  /// stage- token.
  final Color cueBreath;
  /// Slow-down arrow, its gutter bar and the tint of a slower run. Studio only; the stage uses the
  /// matching stage- token.
  final Color cueSlower;
  /// Speed-up arrow, its gutter bar and the tint of a faster run. Studio only; the stage uses the
  /// matching stage- token.
  final Color cueFaster;
  /// Words in an energy lift and the bolt that opens the run. Studio only; the stage uses the
  /// matching stage- token.
  final Color cueEnergy;
  /// Background behind the words of a slower run.
  final Color tintSlower;
  /// Background behind the words of a faster run.
  final Color tintFaster;
  /// Highlight behind the word a sheet is editing.
  final Color tintSelect;
  /// The tally: REC dot, recording timer, stop button. Only while the camera or screen is live.
  final Color rec;
  /// Destructive actions and errors: Delete, failed save.
  final Color danger;
  /// Delivery review: a cue that was delivered (always with a check icon).
  final Color success;
  /// Delivery review: a cue that was missed or rushed (always with an icon).
  final Color warning;
  /// Prompter background. True black, which disappears on beam-splitter glass.
  final Color stage;
  /// Prompter panel over a live camera preview.
  final Color stageScrim;
  /// Script text on stage and stage-scrim. Warm off-white to cut glare.
  final Color stageText;
  /// Words above the reading line, already spoken.
  final Color stageTextRead;
  /// The reading line across the prompter.
  final Color stageLine;
  /// Control bar and HUD fill on stage.
  final Color stageChrome;
  /// Labels and icons on stage-chrome and stage.
  final Color stageChromeText;
  /// Stressed words on the stage (13.7:1 on stage).
  final Color stageStress;
  /// Pause glyphs and the PAUSE badge on the stage.
  final Color stagePause;
  /// Breath glyph and the BREATHE badge on the stage.
  final Color stageBreath;
  /// Slow-down label and gutter bar on the stage.
  final Color stageSlower;
  /// Speed-up label and gutter bar on the stage.
  final Color stageFaster;
  /// Energy words and bolt on the stage.
  final Color stageEnergy;
  /// Behind the words of a slower run on the stage.
  final Color stageTintSlower;
  /// Behind the words of a faster run on the stage.
  final Color stageTintFaster;
  /// The tally on the stage and in the HUD.
  final Color stageRec;
  /// Device checks on the stage that passed: the camera is on, the microphone is heard. Always with
  /// a check icon.
  final Color stageOk;
  /// Device checks on the stage that need the user: no sound, the microphone is blocked. Always with
  /// an icon and a way to fix it.
  final Color stageWarn;
  /// Glass surfaces over live content: the HUD, the cursor companion, the prompter panel over a
  /// camera preview. Always with a 16px backdrop blur.
  final Color stageGlass;
  /// The 1px inner edge that lifts glass off what is behind it.
  final Color stageGlassEdge;
  /// Captions burned into the video. Always with the caption shadow for legibility on any footage.
  final Color captionText;
  /// Optional plate behind Karaoke captions on busy footage.
  final Color captionPlate;
  /// Karaoke words that have not started; fixed half-white on the caption plate.
  final Color captionWaiting;
  /// Click ripples and the cursor halo in edited screen recordings (the cue amber, fixed across
  /// themes).
  final Color ripple;
  /// Floating surfaces only: the recording HUD, the prompter window, sheets. Cards use borders, not
  /// shadows.
  final List<BoxShadow> shadowFloat;

  static const light = SaPalette(
    paper: Color(0xFFF4F5F7),
    surface: Color(0xFFFFFFFF),
    surfaceSunk: Color(0xFFECEEF2),
    line: Color(0xFFD9DCE3),
    lineStrong: Color(0xFF7F8594),
    ink: Color(0xFF15171C),
    ink2: Color(0xFF4A4F5C),
    ink3: Color(0xFF646A78),
    primary: Color(0xFF15171C),
    onPrimary: Color(0xFFFFFFFF),
    cue: Color(0xFFFFC21A),
    onCue: Color(0xFF15171C),
    focus: Color(0xFF15171C),
    cueStress: Color(0xFF935F00),
    cuePause: Color(0xFF6B45D9),
    cueBreath: Color(0xFF0E7F5B),
    cueSlower: Color(0xFF0B67B5),
    cueFaster: Color(0xFFB93E0C),
    cueEnergy: Color(0xFFB8175F),
    tintSlower: Color(0x1F0B67B5),
    tintFaster: Color(0x1FB93E0C),
    tintSelect: Color(0x1415171C),
    rec: Color(0xFFC8261A),
    danger: Color(0xFFC4291C),
    success: Color(0xFF157A45),
    warning: Color(0xFF8F5400),
    stage: Color(0xFF000000),
    stageScrim: Color(0xB3000000),
    stageText: Color(0xFFF2F2EE),
    stageTextRead: Color(0x57F2F2EE),
    stageLine: Color(0x24FFFFFF),
    stageChrome: Color(0xFF1C1D21),
    stageChromeText: Color(0xFFC9CBD1),
    stageStress: Color(0xFFFFC940),
    stagePause: Color(0xFFB79CFF),
    stageBreath: Color(0xFF4FE0B0),
    stageSlower: Color(0xFF5CB8FF),
    stageFaster: Color(0xFFFF8A3D),
    stageEnergy: Color(0xFFFF6BA8),
    stageTintSlower: Color(0x2E5CB8FF),
    stageTintFaster: Color(0x2EFF8A3D),
    stageRec: Color(0xFFFF4D42),
    stageOk: Color(0xFF4ADE80),
    stageWarn: Color(0xFFFFB547),
    stageGlass: Color(0xB816171B),
    stageGlassEdge: Color(0x1FFFFFFF),
    captionText: Color(0xFFFFFFFF),
    captionPlate: Color(0xA6000000),
    captionWaiting: Color(0x80FFFFFF),
    ripple: Color(0xFFFFC940),
    shadowFloat: [BoxShadow(color: Color(0x2415171C), offset: Offset(0.0, 8.0), blurRadius: 24.0), BoxShadow(color: Color(0x1F15171C), offset: Offset(0.0, 1.0), blurRadius: 2.0)],
  );

  static const dark = SaPalette(
    paper: Color(0xFF0F1115),
    surface: Color(0xFF171A20),
    surfaceSunk: Color(0xFF0A0C0F),
    line: Color(0xFF262A33),
    lineStrong: Color(0xFF5F6675),
    ink: Color(0xFFECEDEF),
    ink2: Color(0xFFB4B8C2),
    ink3: Color(0xFF8D93A0),
    primary: Color(0xFFECEDEF),
    onPrimary: Color(0xFF15171C),
    cue: Color(0xFFFFC940),
    onCue: Color(0xFF15171C),
    focus: Color(0xFFECEDEF),
    cueStress: Color(0xFFFFC940),
    cuePause: Color(0xFFB79CFF),
    cueBreath: Color(0xFF4FE0B0),
    cueSlower: Color(0xFF5CB8FF),
    cueFaster: Color(0xFFFF8A3D),
    cueEnergy: Color(0xFFFF6BA8),
    tintSlower: Color(0x2E5CB8FF),
    tintFaster: Color(0x2EFF8A3D),
    tintSelect: Color(0x1FECEDEF),
    rec: Color(0xFFFF4D42),
    danger: Color(0xFFFF6B5E),
    success: Color(0xFF4ADE80),
    warning: Color(0xFFFFB547),
    stage: Color(0xFF000000),
    stageScrim: Color(0xB3000000),
    stageText: Color(0xFFF2F2EE),
    stageTextRead: Color(0x57F2F2EE),
    stageLine: Color(0x24FFFFFF),
    stageChrome: Color(0xFF1C1D21),
    stageChromeText: Color(0xFFC9CBD1),
    stageStress: Color(0xFFFFC940),
    stagePause: Color(0xFFB79CFF),
    stageBreath: Color(0xFF4FE0B0),
    stageSlower: Color(0xFF5CB8FF),
    stageFaster: Color(0xFFFF8A3D),
    stageEnergy: Color(0xFFFF6BA8),
    stageTintSlower: Color(0x2E5CB8FF),
    stageTintFaster: Color(0x2EFF8A3D),
    stageRec: Color(0xFFFF4D42),
    stageOk: Color(0xFF4ADE80),
    stageWarn: Color(0xFFFFB547),
    stageGlass: Color(0xB816171B),
    stageGlassEdge: Color(0x1FFFFFFF),
    captionText: Color(0xFFFFFFFF),
    captionPlate: Color(0xA6000000),
    captionWaiting: Color(0x80FFFFFF),
    ripple: Color(0xFFFFC940),
    shadowFloat: [BoxShadow(color: Color(0x80000000), offset: Offset(0.0, 8.0), blurRadius: 24.0), BoxShadow(color: Color(0x66000000), offset: Offset(0.0, 1.0), blurRadius: 2.0)],
  );
}

/// Spacing steps (4px base).
abstract final class SaSpace {
  /// Glyph-to-word gap, icon-to-label gap.
  static const double s1 = 4.0;
  /// Between chips; inside compact controls.
  static const double s2 = 8.0;
  /// Card and sheet inner gaps.
  static const double s3 = 12.0;
  /// Screen side gutter on phones; card padding.
  static const double s4 = 16.0;
  /// Between sections; desktop gutter.
  static const double s5 = 24.0;
  /// Between groups on large screens.
  static const double s6 = 32.0;
  /// Empty-state padding; prompter side gutter on desktop.
  static const double s7 = 48.0;
  /// Largest step: stage top padding above the first line.
  static const double s8 = 64.0;
}

/// Corner radii.
abstract final class SaRadius {
  /// Tints behind words and selection highlights.
  static const double xs = 4.0;
  /// Chips, cue pills, small buttons.
  static const double sm = 8.0;
  /// Buttons, inputs, cards.
  static const double md = 12.0;
  /// Sheets, dialogs, the recording HUD.
  static const double lg = 20.0;
  /// The record button, hold badges, the camera bubble.
  static const double full = 999.0;
}

/// Fixed durations, for fades and colour changes.
///
/// Motion timing. Motion that carries delivery timing (the scroll, hold badges, countdown) is
/// exempt from these and follows the delivery timeline.
abstract final class SaDurations {
  /// Press feedback on buttons and keys.
  static const Duration instant = Duration(milliseconds: 90);
  /// Toggles, chips, accepting a cue, hold badges appearing.
  static const Duration quick = Duration(milliseconds: 160);
  /// Sheets, dialogs, tab changes, the record-button morph.
  static const Duration base = Duration(milliseconds: 240);
  /// Going on stage: Studio chrome fades out and the stage dims in.
  static const Duration slow = Duration(milliseconds: 400);
  /// One countdown beat.
  static const Duration beat = Duration(milliseconds: 1000);
  /// Refresh click-through around the recording HUD's interactive controls.
  static const Duration hudHitPoll = Duration(milliseconds: 16);
  /// Sample transient pointer position for the companion spring. Never stored.
  static const Duration companionPoll = Duration(milliseconds: 16);
  /// Pointer stillness before the companion returns under the lens.
  static const Duration companionRest = Duration(milliseconds: 2000);
  /// Delay between cues when a markup pass draws in; cap the whole pass at 800ms.
  static const Duration stagger = Duration(milliseconds: 18);
  /// Check live-preview size and source availability; this does not drive capture frames.
  static const Duration previewPoll = Duration(milliseconds: 250);
  /// Original speech before and after a filler phrase audition; not an animation duration.
  static const Duration reviewContext = Duration(milliseconds: 600);
  /// Read recording state and microphone level for the HUD and Voice pace; capture uses its own
  /// clock.
  static const Duration recordingPoll = Duration(milliseconds: 50);
}

/// Easing curves.
abstract final class SaEasing {
  /// Things that move into place: sheets, badges, cues.
  static const Curve standard = Cubic(0.2, 0.0, 0.0, 1.0);
  /// Things that leave: closing sheets, the Studio chrome going on stage.
  static const Curve exit = Cubic(0.3, 0.0, 1.0, 1.0);
  /// Press, toggle and morph.
  static const Curve press = Cubic(0.4, 0.0, 0.2, 1.0);
  /// The prompter scroll within a line. Speed changes between runs blend over 300ms.
  static const Curve scroll = Curves.linear;
}

/// Springs for everything a person touches or the take drives.
///
/// Physical motion as mass stiffness damping, as Flutter's SpringDescription takes them. Springs,
/// not fixed durations, drive everything that moves in response to a person or to the take.
abstract final class SaSprings {
  /// Presses, toggles, chips, cue glyphs arriving (damping ratio 0.79, about 250ms).
  static const SpringDescription snappy = SpringDescription(mass: 1.0, stiffness: 520.0, damping: 36.0);
  /// Sheets, cards, shared-element moves between screens (critically damped, about 400ms, no
  /// overshoot).
  static const SpringDescription smooth = SpringDescription(mass: 1.0, stiffness: 260.0, damping: 32.0);
  /// The one bouncy spring: stressed words popping in captions and on the prompter (damping ratio
  /// 0.46, one visible overshoot).
  static const SpringDescription pop = SpringDescription(mass: 1.0, stiffness: 380.0, damping: 18.0);
  /// Zooms and pans in edited screen recordings, and camera punch-ins (critically damped, about
  /// 650ms).
  static const SpringDescription camera = SpringDescription(mass: 1.0, stiffness: 90.0, damping: 19.0);
  /// The cursor companion trailing the pointer (critically damped, about 450ms of lag).
  static const SpringDescription follow = SpringDescription(mass: 1.0, stiffness: 140.0, damping: 24.0);
}

/// Layout constants of the stage.
///
/// Layout constants of the stage.
abstract final class SaPrompter {
  /// Height of the reading line from the top of the prompter. Adjustable 20% to 45%.
  static const double readingLine = 0.3;
  /// Widest text column under a camera, so eye movement stays invisible on camera.
  static const double columnMax = 34.0;
  /// Leading gutter for pace bars and the reading caret (20px min, 64px max).
  static const double gutter = 0.06;
  /// Opacity of the words above the reading line.
  static const double readFade = 0.35;
  /// Initial logical width of the excluded desktop prompter.
  static const double floatingWidth = 720.0;
  /// Initial logical height of the excluded desktop prompter.
  static const double floatingHeight = 360.0;
  /// Smallest excluded prompter width that keeps its controls readable.
  static const double floatingMinWidth = 640.0;
  /// Smallest excluded prompter height that leaves room for the reading line.
  static const double floatingMinHeight = 280.0;
  /// Lowest desktop prompter opacity. The capture exclusion applies at every opacity.
  static const double floatingMinOpacity = 0.6;
  /// Excluded recording HUD width, with timer, microphone and controls.
  static const double hudWidth = 720.0;
  /// Excluded recording HUD height.
  static const double hudHeight = 96.0;
  /// Protected HUD height while choosing camera companion behaviour.
  static const double hudQuestionHeight = 240.0;
  /// Logical width of the compact cursor reader.
  static const double companionWidth = 440.0;
  /// Logical height of the compact cursor reader.
  static const double companionHeight = 256.0;
  /// Clear space between the cursor and the trailing reader.
  static const double companionGap = 24.0;
  /// Native glass-card opacity; regular reader retains its chosen opacity.
  static const double companionOpacity = 0.9;
  /// Pointer movement needed to change trailing side or reset stillness.
  static const double companionJitter = 4.0;
  /// Excluded countdown size before the HUD docks at the bottom.
  static const double countdownWindowSize = 320.0;
  /// Live microphone meter in the recording HUD.
  static const double micMeterHeight = 3.0;
  /// Diameter of the excluded desktop camera self-view beside the reader.
  static const double cameraBubbleSize = 240.0;
}

/// Defaults for the automatic edit of screen recordings.
///
/// Defaults for the automatic edit of screen recordings.
abstract final class SaScreenFx {
  /// Zoom factor on a click or typing burst.
  static const double zoomDefault = 1.8;
  /// Maximum total duration inside one local screen activity cluster or typing burst.
  static const Duration zoomClusterWindow = Duration(milliseconds: 1300);
  /// Maximum distance from a reliable spoken pointing phrase to a visible click.
  static const Duration zoomPointWindow = Duration(milliseconds: 650);
  /// Lifetime/fade of a click highlight in the edit.
  static const Duration rippleDuration = Duration(milliseconds: 420);
  /// Initial click ring radius at a 1080px short output edge.
  static const double rippleRadius = 10.0;
  /// Maximum click ring growth relative to its starting radius.
  static const double rippleGrow = 4.4;
  /// Click ring stroke at a 1080px short output edge.
  static const double rippleStroke = 3.0;
  /// Soft click halo opacity under the amber ring.
  static const double rippleHalo = 0.12;
  /// Maximum normalized source-axis distance inside one activity cluster.
  static const double zoomClusterDistance = 0.3;
  /// Anonymous key timings needed to count one typing burst.
  static const double zoomTypingMinimum = 3.0;
  /// Largest normalized axis of a measured focused target eligible for zoom-max.
  static const double zoomSmallTarget = 0.12;
  /// Never zoom further; small targets get zoom-max.
  static const double zoomMax = 2.4;
  /// Zooms start this long before the click they frame (the edit knows the future).
  static const Duration zoomLead = Duration(milliseconds: 300);
  /// How long a zoom holds after the last activity before easing out.
  static const Duration zoomHold = Duration(milliseconds: 1400);
  /// Cursor size in the edit, relative to the recorded cursor.
  static const double cursorScale = 1.5;
  /// The cursor fades out after this long without moving.
  static const Duration cursorIdle = Duration(milliseconds: 1500);
  /// Motion blur at the fastest zoom or pan; none when the frame is still.
  static const double blurMax = 6.0;
}

/// Studio take review and video playback.
///
/// Themed Studio take review and video playback.
abstract final class SaReview {
  /// Maximum take preview width; controls remain outside the picture.
  static const double playerMaxWidth = 960.0;
  /// Maximum portrait or landscape preview height in take review.
  static const double playerMaxHeight = 540.0;
}

/// Full-picture local export layout.
///
/// First full-picture Windows export; optional separate camera inset.
abstract final class SaVideoExport {
  /// Camera fits inside this fraction of each output dimension.
  static const double cameraInset = 0.28;
  /// Camera corner margin as a fraction of the shorter output edge.
  static const double cameraMargin = 0.04;
  /// Readable captions' left and wide-format side margins.
  static const double captionEdge = 0.06;
  /// Readable captions' lower-third bottom margin in wide output.
  static const double captionBottom = 0.12;
  /// Vertical caption safe zone above platform UI.
  static const double captionSafeTop = 0.13;
  /// Vertical caption safe zone below platform UI.
  static const double captionSafeBottom = 0.21;
  /// Vertical caption safe zone left of platform UI.
  static const double captionSafeRight = 0.14;
  /// Minimum readable caption size at a 1080px short output edge.
  static const double captionMinSize = 28.0;
  /// Readable captions' tight vertical shadow, scaled with output.
  static const double captionShadowOffset = 2.0;
  /// Karaoke's amber word sweep thickness at a 1080px short edge.
  static const double captionUnderlineSize = 3.0;
  /// Karaoke's word sweep sits below each stable shaped line.
  static const double captionUnderlineGap = 3.0;
  /// Cue word entry translation at a 1080px short edge.
  static const double captionRise = 10.0;
  /// Stress starts compact, driven by the pop spring.
  static const double captionPopStart = 0.55;
  /// Maximum reserved word motion envelope; no reflow or clipping.
  static const double captionPopMax = 1.22;
  /// Normalized pop-spring impulse on stressed words.
  static const double captionPopAmplitude = 0.22;
  /// Punch chunks enter compact on the pop spring.
  static const double captionPunchStart = 0.8;
  /// Anybody width axis on stressed Cue/Karaoke words.
  static const double captionStressWidth = 125.0;
  /// Anybody width axis on a standalone stressed Punch word.
  static const double captionPunchWidth = 135.0;
  /// Anybody width axis for accepted slower caption words.
  static const double captionSlowerWidth = 118.0;
  /// Anybody width axis for accepted faster caption words.
  static const double captionFasterWidth = 82.0;
  /// Total de-click envelope at an internal discontinuous sound join; half on each side, with no
  /// clock overlap.
  static const Duration audioJoinFade = Duration(milliseconds: 20);
}

/// The four type voices: display, reading, signal and pencil.
abstract final class SaFonts {
  static const display = 'Anybody';
  static const displayFallback = <String>['Reem Kufi'];
  static const reading = 'Readex Pro';
  static const readingFallback = <String>[];
  static const signal = 'Martian Mono';
  static const signalFallback = <String>[];
  static const pencil = 'Caveat';
  static const pencilFallback = <String>['Aref Ruqaa'];
}

/// Every type style, by its token name.
abstract final class SaType {
  /// Studio: Empty states, the export screen and the wordmark, in Anybody at width 112. One per
  /// screen at most.
  static const display = TextStyle(
    fontFamily: SaFonts.display,
    fontFamilyFallback: SaFonts.displayFallback,
    fontSize: 40.0,
    height: 1.1,
    fontWeight: FontWeight.w800,
    letterSpacing: -0.8,
  );
  /// Studio: Screen and script titles, in Anybody at width 100.
  static const titleLg = TextStyle(
    fontFamily: SaFonts.display,
    fontFamilyFallback: SaFonts.displayFallback,
    fontSize: 28.0,
    height: 1.2143,
    fontWeight: FontWeight.w700,
  );
  /// Studio: Section and sheet titles.
  static const title = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 20.0,
    height: 1.3,
    fontWeight: FontWeight.w600,
  );
  /// Studio: Default UI text.
  static const body = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 16.0,
    height: 1.5,
    fontWeight: FontWeight.w400,
  );
  /// Studio: List subtitles, helper text, card notes.
  static const bodySm = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 14.0,
    height: 1.4286,
    fontWeight: FontWeight.w400,
  );
  /// Studio: Buttons, chips, tabs. Sentence case.
  static const label = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 13.0,
    height: 1.2308,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.13,
  );
  /// Studio: Meta text under controls.
  static const caption = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 12.0,
    height: 1.3333,
    fontWeight: FontWeight.w400,
  );
  /// Script: Script text in the editor's Marks view (Latin). Room between lines for cue glyphs.
  static const scriptEdit = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 22.0,
    height: 1.6818,
    fontWeight: FontWeight.w400,
  );
  /// Script: Script text in the editor for Arabic: taller lines for Arabic ascenders and marks.
  static const scriptEditAr = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 22.0,
    height: 1.8182,
    fontWeight: FontWeight.w400,
  );
  /// Stage: Prompter over a phone camera preview, or a small desktop window.
  static const stageS = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 32.0,
    height: 1.4375,
    fontWeight: FontWeight.w500,
  );
  /// Stage: Default prompter size.
  static const stageM = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 44.0,
    height: 1.4545,
    fontWeight: FontWeight.w500,
  );
  /// Stage: Prompter read from 1.5 to 3 m, or on teleprompter glass.
  static const stageL = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 60.0,
    height: 1.45,
    fontWeight: FontWeight.w500,
  );
  /// Stage: Beyond 3 m or on a large monitor.
  static const stageXl = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 80.0,
    height: 1.45,
    fontWeight: FontWeight.w500,
  );
  /// Stage: Default prompter size for Arabic; every stage size gets line height 1.6 in Arabic.
  static const stageMAr = TextStyle(
    fontFamily: SaFonts.reading,
    fontFamilyFallback: SaFonts.readingFallback,
    fontSize: 44.0,
    height: 1.5909,
    fontWeight: FontWeight.w500,
  );
  /// Captions: Cue captions at a 1080px-high frame (scale with the frame): Anybody 700, two lines at
  /// most, lower third. Stressed words widen to 130 and pop.
  static const captionCue = TextStyle(
    fontFamily: SaFonts.display,
    fontFamilyFallback: SaFonts.displayFallback,
    fontSize: 56.0,
    height: 1.1429,
    fontWeight: FontWeight.w700,
  );
  /// Captions: Punch captions for vertical video: Anybody 800, one to three words at a time,
  /// centred. Fast runs condense to width 75, slow runs stretch to 125.
  static const captionPunch = TextStyle(
    fontFamily: SaFonts.display,
    fontFamilyFallback: SaFonts.displayFallback,
    fontSize: 96.0,
    height: 1.0417,
    fontWeight: FontWeight.w800,
    letterSpacing: -1.92,
  );
  /// Captions: Karaoke captions for tutorials: Anybody 600, the whole line, filled word by word.
  static const captionKaraoke = TextStyle(
    fontFamily: SaFonts.display,
    fontFamilyFallback: SaFonts.displayFallback,
    fontSize: 52.0,
    height: 1.1923,
    fontWeight: FontWeight.w600,
  );
  /// Signal: Recording timer, take durations, time left.
  static const timecode = TextStyle(
    fontFamily: SaFonts.signal,
    fontFamilyFallback: SaFonts.signalFallback,
    fontSize: 13.0,
    height: 1.2308,
    fontWeight: FontWeight.w500,
  );
  /// Signal: Words per minute, speed readouts.
  static const meter = TextStyle(
    fontFamily: SaFonts.signal,
    fontFamilyFallback: SaFonts.signalFallback,
    fontSize: 11.0,
    height: 1.2727,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.44,
  );
  /// Signal: Capitalised stage labels: hold badges, REC, Hidden from recording.
  static const signalLabel = TextStyle(
    fontFamily: SaFonts.signal,
    fontFamilyFallback: SaFonts.signalFallback,
    fontSize: 11.0,
    height: 1.2727,
    fontWeight: FontWeight.w700,
    letterSpacing: 1.54,
  );
  /// Pencil: The director's margin notes beside cues in the editor. Lower case, never more than six
  /// words.
  static const note = TextStyle(
    fontFamily: SaFonts.pencil,
    fontFamilyFallback: SaFonts.pencilFallback,
    fontSize: 20.0,
    height: 1.1,
    fontWeight: FontWeight.w600,
  );
  /// Pencil: Margin notes in Arabic scripts, in Aref Ruqaa.
  static const noteAr = TextStyle(
    fontFamily: SaFonts.pencil,
    fontFamilyFallback: SaFonts.pencilFallback,
    fontSize: 18.0,
    height: 1.4444,
    fontWeight: FontWeight.w400,
  );
  /// Countdown: Countdown numerals: arrive at width 150, settle to 100 within the beat.
  static const countdown = TextStyle(
    fontFamily: SaFonts.display,
    fontFamilyFallback: SaFonts.displayFallback,
    fontSize: 120.0,
    height: 1.0,
    fontWeight: FontWeight.w900,
  );
}
