// Generates lib/src/theme/tokens.g.dart from the design language's
// tokens (docs/design/tokens.json), so the app and the design system share
// one source of truth. Run it from app/ after changing the tokens:
//
//   dart run tool/gen_tokens.dart
//
// test/theme/tokens_test.dart fails when the generated file is stale.

import 'dart:convert';
import 'dart:io';

const tokensPath = '../docs/design/tokens.json';
const outputPath = 'lib/src/theme/tokens.g.dart';

/// The font families bundled in pubspec.yaml. A CSS stack keeps only these:
/// the first is the family, the rest its fallbacks.
const bundledFamilies = {'Anybody', 'Readex Pro', 'Martian Mono', 'Caveat', 'Aref Ruqaa', 'Reem Kufi'};

void main() {
  final json = jsonDecode(File(tokensPath).readAsStringSync()) as Map<String, dynamic>;
  File(outputPath).writeAsStringSync(generateTokens(json));
  stdout.writeln('Wrote $outputPath');
}

String generateTokens(Map<String, dynamic> t) {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_tokens.dart from docs/design/tokens.json. Do not edit:')
    ..writeln('// change the tokens there, then run `dart run tool/gen_tokens.dart` from app/.')
    ..writeln()
    ..writeln("import 'package:flutter/animation.dart';")
    ..writeln("import 'package:flutter/painting.dart';")
    ..writeln();

  // ---- colours and shadows, per theme ----
  final colors = (t['color']['tokens'] as List).cast<Map<String, dynamic>>();
  final shadows = ((t['shadow']?['tokens'] ?? []) as List).cast<Map<String, dynamic>>();
  out
    ..writeln('/// Every colour and shadow token in one theme: Studio light or Studio dark.')
    ..writeln('/// The stage, caption and ripple colours are the same in both.')
    ..writeln('class SaPalette {')
    ..writeln('  const SaPalette({');
  for (final c in [...colors, ...shadows]) {
    out.writeln('    required this.${_camel(c['name'] as String)},');
  }
  out.writeln('  });');
  for (final c in colors) {
    _doc(out, c['usage'] as String?, '  ');
    out.writeln('  final Color ${_camel(c['name'] as String)};');
  }
  for (final s in shadows) {
    _doc(out, s['usage'] as String?, '  ');
    out.writeln('  final List<BoxShadow> ${_camel(s['name'] as String)};');
  }
  for (final theme in ['light', 'dark']) {
    out
      ..writeln()
      ..writeln('  static const $theme = SaPalette(');
    for (final c in colors) {
      out.writeln('    ${_camel(c['name'] as String)}: ${_color(_themed(c['value'], theme))},');
    }
    for (final s in shadows) {
      out.writeln('    ${_camel(s['name'] as String)}: ${_shadow(_themed(s['value'], theme))},');
    }
    out.writeln('  );');
  }
  out
    ..writeln('}')
    ..writeln();

  // ---- plain families ----
  void family(String key, String className, String doc, String prefix, (String, String) Function(String) typed,
      {String namePrefix = ''}) {
    final fam = t[key] as Map<String, dynamic>?;
    if (fam == null) return;
    out.writeln('/// $doc');
    if (fam['note'] != null) {
      out.writeln('///');
      _doc(out, fam['note'] as String, '');
    }
    out.writeln('abstract final class $className {');
    for (final tok in (fam['tokens'] as List).cast<Map<String, dynamic>>()) {
      var name = tok['name'] as String;
      if (name.startsWith(prefix)) name = name.substring(prefix.length);
      _doc(out, tok['usage'] as String?, '  ');
      final (type, value) = typed(tok['value'].toString());
      out.writeln('  static const $type $namePrefix${_camel(name)} = $value;');
    }
    out
      ..writeln('}')
      ..writeln();
  }

  family('spacing', 'SaSpace', 'Spacing steps (4px base).', 'space-', (v) => ('double', _px(v)), namePrefix: 's');
  family('radius', 'SaRadius', 'Corner radii.', 'radius-', (v) => ('double', _px(v)));
  family('duration', 'SaDurations', 'Fixed durations, for fades and colour changes.', 'dur-', (v) => ('Duration', _ms(v)));
  family('easing', 'SaEasing', 'Easing curves.', 'ease-', (v) => ('Curve', _curve(v)));
  family('spring', 'SaSprings', 'Springs for everything a person touches or the take drives.', 'spring-',
      (v) => ('SpringDescription', _spring(v)));
  family('prompter', 'SaPrompter', 'Layout constants of the stage.', '', _number);
  family('screen-fx', 'SaScreenFx', 'Defaults for the automatic edit of screen recordings.', '', _number);
  family('review', 'SaReview', 'Studio take review and video playback.', '', _number);

  // ---- type ----
  final type = t['type'] as Map<String, dynamic>;
  final families = (type['families'] as Map<String, dynamic>).map((k, v) => MapEntry(k, _stack(v as String)));
  out
    ..writeln('/// The four type voices: display, reading, signal and pencil.')
    ..writeln('abstract final class SaFonts {');
  families.forEach((key, stack) {
    out
      ..writeln("  static const ${_camel(key)} = '${stack.first}';")
      ..writeln('  static const ${_camel(key)}Fallback = <String>[${stack.skip(1).map((f) => "'$f'").join(', ')}];');
  });
  out
    ..writeln('}')
    ..writeln()
    ..writeln('/// Every type style, by its token name.')
    ..writeln('abstract final class SaType {');
  for (final group in (type['groups'] as List).cast<Map<String, dynamic>>()) {
    for (final s in (group['styles'] as List).cast<Map<String, dynamic>>()) {
      final fam = _camel((s['family'] ?? group['family']) as String);
      final size = _pxValue(s['fontSize'] as String);
      final line = s['lineHeight'];
      final height = line is num ? line.toDouble() : _pxValue(line as String) / size;
      final spacing = s['letterSpacing'] == null ? null : _emValue(s['letterSpacing'] as String) * size;
      _doc(out, '${group['name']}: ${s['usage'] ?? ''}', '  ');
      out
        ..writeln('  static const ${_camel(s['name'] as String)} = TextStyle(')
        ..writeln('    fontFamily: SaFonts.$fam,')
        ..writeln('    fontFamilyFallback: SaFonts.${fam}Fallback,')
        ..writeln('    fontSize: ${_num(size)},')
        ..writeln('    height: ${_num(height)},')
        ..writeln('    fontWeight: FontWeight.w${s['fontWeight']},');
      if (spacing != null) out.writeln('    letterSpacing: ${_num(spacing)},');
      out.writeln('  );');
    }
  }
  out.writeln('}');
  return out.toString();
}

Object _themed(Object? value, String theme) => value is Map ? (value[theme] ?? value.values.first) as Object : value!;

String _camel(String name) {
  final parts = name.split(RegExp(r'[-_.]'));
  return parts.first + parts.skip(1).map((p) => p.isEmpty ? '' : p[0].toUpperCase() + p.substring(1)).join();
}

String _color(Object value) {
  final v = (value as String).toLowerCase();
  final m = RegExp(r'^#([0-9a-f]{6})([0-9a-f]{2})?$').firstMatch(v);
  if (m == null) throw FormatException('Unsupported colour $v');
  return 'Color(0x${(m.group(2) ?? 'ff').toUpperCase()}${m.group(1)!.toUpperCase()})';
}

String _shadow(Object value) {
  final layers = (value as String).split(RegExp(r',\s*(?![^()]*\))'));
  final shadows = layers.map((layer) {
    final m = RegExp(r'^\s*(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+([\d.]+)(?:px)?\s+rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)\s*$')
        .firstMatch(layer);
    if (m == null) throw FormatException('Unsupported shadow $layer');
    final alpha = (double.parse(m.group(7)!) * 255).round();
    final rgb = [4, 5, 6].map((i) => int.parse(m.group(i)!).toRadixString(16).padLeft(2, '0')).join().toUpperCase();
    return 'BoxShadow(color: Color(0x${alpha.toRadixString(16).padLeft(2, '0').toUpperCase()}$rgb), '
        'offset: Offset(${_num(double.parse(m.group(1)!))}, ${_num(double.parse(m.group(2)!))}), '
        'blurRadius: ${_num(double.parse(m.group(3)!))})';
  });
  return '[${shadows.join(', ')}]';
}

double _pxValue(String v) => double.parse(v.replaceAll('px', ''));

double _emValue(String v) => double.parse(v.replaceAll('em', ''));

String _px(String v) => _num(_pxValue(v));

String _ms(String v) => 'Duration(milliseconds: ${int.parse(v.replaceAll('ms', ''))})';

String _curve(String v) {
  if (v == 'linear') return 'Curves.linear';
  final m = RegExp(r'cubic-bezier\(([^)]*)\)').firstMatch(v);
  if (m == null) throw FormatException('Unsupported easing $v');
  return 'Cubic(${m.group(1)!.split(',').map((p) => _num(double.parse(p.trim()))).join(', ')})';
}

String _spring(String v) {
  final p = v.trim().split(RegExp(r'\s+')).map(double.parse).toList();
  return 'SpringDescription(mass: ${_num(p[0])}, stiffness: ${_num(p[1])}, damping: ${_num(p[2])})';
}

/// Milliseconds become durations, percentages fractions; px and ch drop their unit.
(String, String) _number(String v) {
  if (v.endsWith('ms')) return ('Duration', _ms(v));
  if (v.endsWith('%')) return ('double', _num(double.parse(v.substring(0, v.length - 1)) / 100));
  return ('double', _num(double.parse(v.replaceAll(RegExp(r'(px|ch)$'), ''))));
}

String _num(double v) {
  final s = v.toStringAsFixed(4).replaceFirst(RegExp(r'0+$'), '');
  return s.endsWith('.') ? '${s}0' : s;
}

List<String> _stack(String css) {
  final names = css.split(',').map((f) => f.trim().replaceAll('"', '').replaceAll("'", '')).toList();
  final kept = names.where(bundledFamilies.contains).toList();
  if (kept.isEmpty) throw FormatException('No bundled font in $css');
  return kept;
}

void _doc(StringBuffer out, String? text, String indent) {
  if (text == null || text.isEmpty) return;
  final words = text.split(' ');
  var line = StringBuffer();
  for (final w in words) {
    if (line.length + w.length + 1 > 96 && line.isNotEmpty) {
      out.writeln('$indent/// ${line.toString().trimRight()}');
      line = StringBuffer();
    }
    line.write('$w ');
  }
  if (line.isNotEmpty) out.writeln('$indent/// ${line.toString().trimRight()}');
}
